package com.jomac.transcription.reference.forms;

import com.jomac.transcription.reference.Main;
import java.awt.Font;
import java.util.prefs.Preferences;
import javax.swing.SpinnerNumberModel;

public class PreferenceDialog extends javax.swing.JDialog {

    private boolean modified;
    private final int SYSTEM_FONT_SIZE = 14;
    private final int DOCUMENT_FONT_SIZE = 16;
    private Preferences preferences;

    public PreferenceDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        spSystem.setModel(new SpinnerNumberModel(SYSTEM_FONT_SIZE, 10, 26, 2));
        spDocument.setModel(new SpinnerNumberModel(DOCUMENT_FONT_SIZE, 10, 36, 2));
        loadPreference();

        if (parent != null) {
            this.setLocationRelativeTo(parent);
        }
    }

    public boolean isModified() {
        return modified;
    }

    public void setModified(boolean modified) {
        this.modified = modified;
    }

    private void loadPreference() {
        preferences = Main.getPreferences();
        int systemFont = preferences.getInt("systemF", SYSTEM_FONT_SIZE);
        spSystem.setValue(systemFont);
        spDocument.setValue(preferences.getInt("documentF", DOCUMENT_FONT_SIZE));
        setDialogFontSize(systemFont);
    }

    private void setDialogFontSize(int fontSize) {
        Font font = new Font("Tahoma", Font.PLAIN, fontSize);
        lblSFontSize.setFont(font);
        lblDFontSize.setFont(font);
        spSystem.setFont(font);
        spDocument.setFont(font);

    }

    private void savePreference(boolean setDefault) {
        preferences.putInt("systemF", setDefault ? SYSTEM_FONT_SIZE
                : Integer.parseInt(spSystem.getValue().toString()));
        preferences.putInt("documentF", setDefault ? DOCUMENT_FONT_SIZE
                : Integer.parseInt(spDocument.getValue().toString()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pnlSystem = new javax.swing.JPanel();
        lblSFontSize = new javax.swing.JLabel();
        spSystem = new javax.swing.JSpinner();
        pnlDocument = new javax.swing.JPanel();
        lblDFontSize = new javax.swing.JLabel();
        spDocument = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        btnOk = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Preference");
        setIconImage(null);
        setResizable(false);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        pnlSystem.setBorder(javax.swing.BorderFactory.createTitledBorder("System Font"));
        pnlSystem.setLayout(new java.awt.GridBagLayout());

        lblSFontSize.setText("Font Size:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        pnlSystem.add(lblSFontSize, gridBagConstraints);

        spSystem.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        pnlSystem.add(spSystem, gridBagConstraints);

        jPanel2.add(pnlSystem);

        pnlDocument.setBorder(javax.swing.BorderFactory.createTitledBorder("Document Font"));
        pnlDocument.setLayout(new java.awt.GridBagLayout());

        lblDFontSize.setText("Font Size:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        pnlDocument.add(lblDFontSize, gridBagConstraints);

        spDocument.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        pnlDocument.add(spDocument, gridBagConstraints);

        jPanel2.add(pnlDocument);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnOk.setText("OK");
        btnOk.setPreferredSize(new java.awt.Dimension(70, 25));
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        jPanel3.add(btnOk);

        btnReset.setText("Reset to Default");
        btnReset.setPreferredSize(new java.awt.Dimension(111, 25));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel3.add(btnReset);

        btnCancel.setText("Cancel");
        btnCancel.setPreferredSize(new java.awt.Dimension(70, 25));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel3.add(btnCancel);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        modified = false;
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        modified = true;
        savePreference(false);
        this.dispose();
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        modified = true;
        savePreference(true);
        this.dispose();
    }//GEN-LAST:event_btnResetActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnReset;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblDFontSize;
    private javax.swing.JLabel lblSFontSize;
    private javax.swing.JPanel pnlDocument;
    private javax.swing.JPanel pnlSystem;
    private javax.swing.JSpinner spDocument;
    private javax.swing.JSpinner spSystem;
    // End of variables declaration//GEN-END:variables
}
